stages:
  - build
  - dockerize
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  SPRING_PROFILES_ACTIVE: dev
  IMAGE_NAME: quay.io/kodekollab/demo:03
  # REGISTRY: docker.io
  # DOCKERHUB_USERNAME: yourdockerhubusername
  # DOCKERHUB_PASSWORD: yourdockerhubpassword

build:
  stage: build
  image: maven:3.8.2-openjdk-17-slim
  tags:
    - gitlabrunner
  script:
    - mvn clean package -B
  artifacts:
    paths:
    - target/
    expire_in: 1 hours


dockerize:
  stage: dockerize
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags:
    - gitlabrunner
  script:
    - echo "Building and pushing Docker image"
    - echo "{\"auths\":{\"$REGISTRY_QUAY\":{\"username\":\"$REGISTRY_USER\",\"password\":\"$REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    #- echo "{\"auths\":{\"docker.io\":{\"auth\":\"${BASE64_ENCODED_AUTH}\"}}}" > /kaniko/.docker/config.json
    #- cat /kaniko/.docker/config.json
    - /kaniko/executor --context ${CI_PROJECT_DIR} --dockerfile ${CI_PROJECT_DIR}/Dockerfile --destination ${IMAGE_NAME}
  artifacts:
    paths: 
    - target/
    expire_in: 1 hours


deploy:
  stage: deploy
  image: alpine/git
  tags:
    - gitlabrunner
  script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$GITLAB_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan kollab.innospheres.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git config --global user.email "developer@kodekollab.com"
    - git config --global user.name "developer"
    - git clone git@kollab.innospheres.com:developer/k8s.git
    - cd k8s
    #- sed -i 's|image: rameshpala/quizzapp:6.0|image: '${IMAGE_NAME}'|' overlays/test/deployment-patch.yaml
    - sed -i 's|quay.io/kodekollab/demo:02|'"${IMAGE_NAME}"'|' overlays/test/deployment-patch.yaml
    - git commit -am "Update image to latest"
    - git push


